import {
  AlertItem,
  AppItem,
  LogConfigItem,
  LogFileItem,
  LogItem,
  MachineItem,
  ModuleItem,
  MonitorPointItem,
  NavCategory,
  PointTypeItem,
  PointViewItem,
  AlarmConfigItem,
} from './types';

// 导航菜单层级结构（严格对应功能目录要求）
export const NAVIGATION_STRUCTURE: NavCategory[] = [
  {
    id: 'home',
    code: '3.2',
    label: '首页模块',
    icon: 'LayoutDashboard',
    directSubItems: [
      {
        id: 'home',
        code: '3.2',
        label: '系统首页总览',
        description: '次级模块快捷跳转与全局运行监控速览',
      },
    ],
  },
  {
    id: 'report-view',
    code: '3.3',
    label: '上报查看',
    icon: 'ActivitySquare',
    groups: [
      {
        id: 'alarm-view',
        code: '3.3.1',
        label: '监控告警查看',
        subItems: [
          {
            id: 'alert-list',
            code: '3.3.1.1',
            label: '监控点告警列表',
            badge: 5,
            badgeColor: 'bg-rose-500',
            description: '告警详情、处理状态追踪与操作栏处置',
          },
        ],
      },
      {
        id: 'log-view',
        code: '3.3.2',
        label: '日志查看',
        subItems: [
          {
            id: 'log-realtime',
            code: '3.3.2.1',
            label: '实时日志查看',
            description: '多条件过滤、实时参数与流式数据监听',
          },
          {
            id: 'log-history',
            code: '3.3.2.2',
            label: '历史日志查看',
            description: '多条件精准搜索、历史参数及上下文堆栈',
          },
          {
            id: 'log-files',
            code: '3.3.2.3',
            label: '日志文件列表',
            description: '文件基础信息与一键快捷跳转历史日志',
          },
        ],
      },
      {
        id: 'plugin-table',
        code: '3.3.3',
        label: '插件实时表格',
        subItems: [
          {
            id: 'plugin-linux',
            code: '3.3.3',
            label: 'Linux基础资源监控',
            description: '系统概况、内存、TCP/UDP及磁盘IO',
          },
        ],
      },
      {
        id: 'plugin-chart',
        code: '3.3.4',
        label: '插件图表',
        subItems: [
          {
            id: 'plugin-browser',
            code: '3.3.4',
            label: '浏览器端监控',
            description: 'OS/浏览器版本、地域分布与API耗时分析',
          },
        ],
      },
      {
        id: 'view-look',
        code: '3.3.5',
        label: '视图查看',
        subItems: [
          {
            id: 'view-common',
            code: '3.3.5.1',
            label: '监控系统-常用',
            description: '时间筛选、日志写入量、登录与CGI请求趋势',
          },
        ],
      },
      {
        id: 'server-look',
        code: '3.3.6',
        label: '服务器查看',
        subItems: [
          {
            id: 'server-status',
            code: '3.3.6',
            label: '服务器运行状态',
            description: '指定日期分析、磁盘写入量、vmem存取及延迟',
          },
        ],
      },
    ],
  },
  {
    id: 'report-mgmt',
    code: '3.4',
    label: '上报管理',
    icon: 'SlidersHorizontal',
    groups: [
      {
        id: 'machine-mgmt',
        code: '3.4.1',
        label: '上报机器管理',
        subItems: [
          {
            id: 'mgmt-machines',
            code: '3.4.1',
            label: '上报机器管理',
            description: '机器列表、增删改、插件部署与详情查看',
          },
        ],
      },
      {
        id: 'point-mgmt',
        code: '3.4.2',
        label: '监控点管理',
        subItems: [
          {
            id: 'mgmt-point-types',
            code: '3.4.2.1',
            label: '监控点类型管理',
            description: '类型编辑、右侧增删改及重填/提交',
          },
          {
            id: 'mgmt-points',
            code: '3.4.2.2',
            label: '监控点管理',
            description: '监控点列表、批量导入与全生命周期维护',
          },
          {
            id: 'mgmt-point-views',
            code: '3.4.2.3',
            label: '监控点视图管理',
            description: '视图列表、ID/关键字搜索及增删改',
          },
          {
            id: 'mgmt-point-alarms',
            code: '3.4.2.4',
            label: '监控点告警配置',
            description: '单机/视图告警、批量修改/屏蔽/解除/删除',
          },
        ],
      },
      {
        id: 'log-source-mgmt',
        code: '3.4.3',
        label: '日志源管理',
        subItems: [
          {
            id: 'mgmt-apps',
            code: '3.4.3.1',
            label: '应用管理',
            description: '应用系统注册、归属团队与详情探查',
          },
          {
            id: 'mgmt-modules',
            code: '3.4.3.2',
            label: '模块管理',
            description: '服务模块注册、健康探针与跨应用管理',
          },
          {
            id: 'mgmt-log-configs',
            code: '3.4.3.3',
            label: '日志配置管理',
            description: '频控限制、日志模式定义与上报策略',
          },
        ],
      },
    ],
  },
];

// 3.3.1 告警数据
export const INITIAL_ALERTS: AlertItem[] = [
  {
    id: 'ALT-10921',
    pointId: 'PT-CPU-001',
    pointName: 'CPU使用率突增',
    level: 'CRITICAL',
    currentValue: 94.8,
    threshold: 85.0,
    unit: '%',
    machineIp: '10.24.12.88',
    moduleName: 'user-auth-service',
    occurredTime: '2026-09-09 22:15:32',
    duration: '14分钟',
    status: 'UNCLAIMED',
  },
  {
    id: 'ALT-10920',
    pointId: 'PT-MEM-003',
    pointName: 'JVM老年代内存越界',
    level: 'MAJOR',
    currentValue: 88.5,
    threshold: 80.0,
    unit: '%',
    machineIp: '10.24.12.90',
    moduleName: 'order-pay-gateway',
    occurredTime: '2026-09-09 21:40:18',
    duration: '49分钟',
    status: 'PROCESSING',
    handler: '李运维 (ops_li)',
    handleNotes: '正在dump内存堆快照分析内存泄露点',
  },
  {
    id: 'ALT-10919',
    pointId: 'PT-TCP-008',
    pointName: 'TCP TIME_WAIT堆积',
    level: 'WARNING',
    currentValue: 8420,
    threshold: 6000,
    unit: '条',
    machineIp: '10.24.14.12',
    moduleName: 'api-proxy-nginx',
    occurredTime: '2026-09-09 20:05:04',
    duration: '2小时24分',
    status: 'PROCESSING',
    handler: '张工程师 (zhang_dev)',
    handleNotes: '正在调整内核 net.ipv4.tcp_tw_reuse 参数',
  },
  {
    id: 'ALT-10918',
    pointId: 'PT-DISK-002',
    pointName: '数据盘IO写入延迟过高',
    level: 'WARNING',
    currentValue: 64.2,
    threshold: 50.0,
    unit: 'ms',
    machineIp: '10.24.16.55',
    moduleName: 'log-collector-agent',
    occurredTime: '2026-09-09 19:12:30',
    duration: '3小时17分',
    status: 'IGNORED',
    handler: '系统自动过滤',
    handleNotes: '夜间批量数据备份预热属于允许峰值，已人工设置忽略',
  },
  {
    id: 'ALT-10917',
    pointId: 'PT-CGI-005',
    pointName: 'CGI请求错误率波动',
    level: 'MAJOR',
    currentValue: 4.82,
    threshold: 2.0,
    unit: '%',
    machineIp: '10.24.12.89',
    moduleName: 'user-auth-service',
    occurredTime: '2026-09-09 18:30:10',
    duration: '4小时',
    status: 'UNCLAIMED',
  },
  {
    id: 'ALT-10916',
    pointId: 'PT-LOG-009',
    pointName: '单机日志写入频控突发上限',
    level: 'INFO',
    currentValue: 12500,
    threshold: 10000,
    unit: '条/s',
    machineIp: '10.24.18.22',
    moduleName: 'billing-calc-job',
    occurredTime: '2026-09-09 17:00:22',
    duration: '5小时29分',
    status: 'RESOLVED',
    handler: '王专家 (wang_sre)',
    handleNotes: '已调大频控突发缓冲队列并完成验证',
  },
];

// 3.3.2 日志数据
export const INITIAL_LOGS: LogItem[] = [
  {
    id: 'LOG-884910',
    timestamp: '2026-09-09 23:25:12.842',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    level: 'ERROR',
    machineIp: '10.24.12.88',
    traceId: 'tr-c8f9210-9941a8',
    message: 'User authentication failed: Redis token cluster connection timed out after 3000ms',
    durationMs: 3120,
    httpStatus: 504,
    params: {
      userId: 9812401,
      clientIp: '183.14.132.88',
      authMethod: 'OAuth_JWT',
      retryCount: 3,
    },
    stackTrace: 'java.net.SocketTimeoutException: Read timed out\n  at java.base/java.net.SocketInputStream.socketRead0(Native Method)\n  at io.lettuce.core.protocol.RedisStateMachine.decode(RedisStateMachine.java:142)\n  at com.monitor.auth.service.TokenManager.verify(TokenManager.java:88)',
  },
  {
    id: 'LOG-884909',
    timestamp: '2026-09-09 23:25:10.114',
    app: '商城业务中心 (mall-app)',
    module: 'order-pay-gateway',
    level: 'WARN',
    machineIp: '10.24.12.90',
    traceId: 'tr-71e44a1-0021b2',
    message: 'Upstream payment gateway response latency > 800ms threshold [provider=WXPAY_DIRECT]',
    durationMs: 914,
    httpStatus: 200,
    params: {
      orderSn: 'ORD20260909008129',
      amountCent: 29900,
      currency: 'CNY',
      channel: 'WXPAY_APP',
    },
  },
  {
    id: 'LOG-884908',
    timestamp: '2026-09-09 23:25:08.520',
    app: '公共网关体系 (gateway-core)',
    module: 'api-proxy-nginx',
    level: 'INFO',
    machineIp: '10.24.14.12',
    traceId: 'tr-11a94f0-4421cc',
    message: 'HTTP POST /api/v2/user/session refreshed successfully',
    durationMs: 24,
    httpStatus: 200,
    params: {
      userAgent: 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)',
      remoteAddr: '114.249.21.90',
      sslProtocol: 'TLSv1.3',
    },
  },
  {
    id: 'LOG-884907',
    timestamp: '2026-09-09 23:25:05.102',
    app: '数据智能中台 (data-hub)',
    module: 'log-collector-agent',
    level: 'DEBUG',
    machineIp: '10.24.16.55',
    traceId: 'tr-09a888c-1200fa',
    message: 'Batch flushed 1024 audit metrics to Kafka partition-02 offset 988123',
    durationMs: 12,
    httpStatus: 200,
    params: {
      batchSize: 1024,
      compressRatio: '0.42',
      targetTopic: 'monitor_report_v2',
    },
  },
  {
    id: 'LOG-884906',
    timestamp: '2026-09-09 23:24:58.339',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    level: 'INFO',
    machineIp: '10.24.12.89',
    traceId: 'tr-44bb192-7711ea',
    message: 'CGI Request: queryUserInfoByUid completed',
    durationMs: 38,
    httpStatus: 200,
    params: {
      uid: 559021,
      cacheHit: true,
      fields: ['nickname', 'avatar', 'membership'],
    },
  },
  {
    id: 'LOG-884905',
    timestamp: '2026-09-09 23:24:50.918',
    app: '财务计费系统 (billing-srv)',
    module: 'billing-calc-job',
    level: 'ERROR',
    machineIp: '10.24.18.22',
    traceId: 'tr-99fe112-6632aa',
    message: 'Settlement pipeline deadlock detected on table `t_settlement_ledger_202609`',
    durationMs: 5012,
    httpStatus: 500,
    params: {
      transId: 'TX-99881204',
      lockWaitTimeout: 5000,
      merchantId: 'MCH_99410',
    },
    stackTrace: 'org.springframework.dao.CannotAcquireLockException: Deadlock found when trying to get lock; try restarting transaction\n  at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:130)\n  at com.billing.calc.executor.LedgerTask.execute(LedgerTask.java:214)',
  },
  {
    id: 'LOG-884904',
    timestamp: '2026-09-09 23:24:41.200',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    level: 'WARN',
    machineIp: '10.24.12.88',
    traceId: 'tr-66aa301-8821bb',
    message: 'Excessive password retry for account user_admin_sec (5 attempts in 60s)',
    durationMs: 45,
    httpStatus: 401,
    params: {
      account: 'user_admin_sec',
      ip: '221.192.88.14',
      action: 'TRIGGER_TEMP_CAPTCHA_LOCK',
    },
  },
];

// 3.3.2.3 日志文件列表
export const INITIAL_LOG_FILES: LogFileItem[] = [
  {
    id: 'LF-001',
    fileName: 'user-auth-service.access.2026-09-09.log',
    filePath: '/data/logs/mall-app/user-auth-service/access.log',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    machineIp: '10.24.12.88',
    fileSizeBytes: 489201948,
    fileSizeStr: '466.5 MB',
    lineCount: 1849200,
    lastModified: '2026-09-09 23:25:00',
    isCompressed: false,
  },
  {
    id: 'LF-002',
    fileName: 'user-auth-service.error.2026-09-09.log',
    filePath: '/data/logs/mall-app/user-auth-service/error.log',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    machineIp: '10.24.12.88',
    fileSizeBytes: 12489102,
    fileSizeStr: '11.9 MB',
    lineCount: 42100,
    lastModified: '2026-09-09 23:25:12',
    isCompressed: false,
  },
  {
    id: 'LF-003',
    fileName: 'order-pay-gateway.audit.2026-09-09.log.gz',
    filePath: '/data/logs/mall-app/order-pay-gateway/audit.2026-09-09.log.gz',
    app: '商城业务中心 (mall-app)',
    module: 'order-pay-gateway',
    machineIp: '10.24.12.90',
    fileSizeBytes: 89124801,
    fileSizeStr: '85.0 MB',
    lineCount: 928400,
    lastModified: '2026-09-09 23:00:00',
    isCompressed: true,
  },
  {
    id: 'LF-004',
    fileName: 'api-proxy.access.2026-09-09.log',
    filePath: '/data/logs/gateway-core/api-proxy-nginx/access.log',
    app: '公共网关体系 (gateway-core)',
    module: 'api-proxy-nginx',
    machineIp: '10.24.14.12',
    fileSizeBytes: 1428901239,
    fileSizeStr: '1.33 GB',
    lineCount: 5410920,
    lastModified: '2026-09-09 23:25:08',
    isCompressed: false,
  },
  {
    id: 'LF-005',
    fileName: 'billing-calc.runtime.2026-09-09.log',
    filePath: '/data/logs/billing-srv/billing-calc-job/runtime.log',
    app: '财务计费系统 (billing-srv)',
    module: 'billing-calc-job',
    machineIp: '10.24.18.22',
    fileSizeBytes: 34189012,
    fileSizeStr: '32.6 MB',
    lineCount: 135000,
    lastModified: '2026-09-09 23:24:50',
    isCompressed: false,
  },
];

// 3.4.1 上报机器列表
export const INITIAL_MACHINES: MachineItem[] = [
  {
    id: 'MCH-1001',
    machineId: 'VM-SHANGHAI-PROD-01',
    ip: '10.24.12.88',
    innerIp: '192.168.1.88',
    hostname: 'sh-mall-auth-01.prod',
    env: 'prod',
    datacenter: '上海一区 (BGP)',
    status: 'ONLINE',
    agentVersion: 'v3.8.4',
    pluginStatus: 'DEPLOYED',
    cpuCores: 16,
    memTotalGB: 64,
    diskTotalGB: 1024,
    lastHeartbeat: '2秒前',
    tags: ['用户认证', '高IO负载', '核心'],
  },
  {
    id: 'MCH-1002',
    machineId: 'VM-SHANGHAI-PROD-02',
    ip: '10.24.12.89',
    innerIp: '192.168.1.89',
    hostname: 'sh-mall-auth-02.prod',
    env: 'prod',
    datacenter: '上海一区 (BGP)',
    status: 'ONLINE',
    agentVersion: 'v3.8.4',
    pluginStatus: 'DEPLOYED',
    cpuCores: 16,
    memTotalGB: 64,
    diskTotalGB: 1024,
    lastHeartbeat: '3秒前',
    tags: ['用户认证', '双活冗余'],
  },
  {
    id: 'MCH-1003',
    machineId: 'VM-BEIJING-GATEWAY-01',
    ip: '10.24.14.12',
    innerIp: '192.168.2.12',
    hostname: 'bj-gateway-nginx-01.prod',
    env: 'prod',
    datacenter: '北京二区 (移动/联通)',
    status: 'ONLINE',
    agentVersion: 'v3.8.4',
    pluginStatus: 'DEPLOYED',
    cpuCores: 32,
    memTotalGB: 128,
    diskTotalGB: 2048,
    lastHeartbeat: '1秒前',
    tags: ['入口网关', '超高并发'],
  },
  {
    id: 'MCH-1004',
    machineId: 'VM-GUANGZHOU-PAY-01',
    ip: '10.24.12.90',
    innerIp: '192.168.3.90',
    hostname: 'gz-pay-gateway-01.prod',
    env: 'prod',
    datacenter: '广州专区 (金融云)',
    status: 'ONLINE',
    agentVersion: 'v3.8.2',
    pluginStatus: 'DEPLOYED',
    cpuCores: 16,
    memTotalGB: 64,
    diskTotalGB: 1024,
    lastHeartbeat: '5秒前',
    tags: ['支付专区', 'PCI安全合规'],
  },
  {
    id: 'MCH-1005',
    machineId: 'VM-SHANGHAI-LOG-01',
    ip: '10.24.16.55',
    innerIp: '192.168.1.55',
    hostname: 'sh-data-collector-01.prod',
    env: 'prod',
    datacenter: '上海一区 (BGP)',
    status: 'ONLINE',
    agentVersion: 'v3.8.4',
    pluginStatus: 'DEPLOYED',
    cpuCores: 32,
    memTotalGB: 128,
    diskTotalGB: 4096,
    lastHeartbeat: '4秒前',
    tags: ['日志管道', 'Kafka流式上报'],
  },
  {
    id: 'MCH-1006',
    machineId: 'VM-STAGING-TEST-01',
    ip: '10.24.18.22',
    innerIp: '192.168.9.22',
    hostname: 'staging-worker-01.test',
    env: 'staging',
    datacenter: '开发测试区',
    status: 'ABNORMAL',
    agentVersion: 'v3.7.0',
    pluginStatus: 'UPDATING',
    cpuCores: 8,
    memTotalGB: 32,
    diskTotalGB: 512,
    lastHeartbeat: '45秒前',
    tags: ['测试演练', '插件待升配'],
  },
  {
    id: 'MCH-1007',
    machineId: 'VM-BACKUP-DEV-01',
    ip: '10.24.19.88',
    innerIp: '192.168.9.88',
    hostname: 'dev-sandbox-01.dev',
    env: 'dev',
    datacenter: '开发测试区',
    status: 'OFFLINE',
    agentVersion: 'v3.6.0',
    pluginStatus: 'NOT_DEPLOYED',
    cpuCores: 4,
    memTotalGB: 16,
    diskTotalGB: 256,
    lastHeartbeat: '3天前',
    tags: ['开发临时机'],
  },
];

// 3.4.2.1 监控点类型数据
export const INITIAL_POINT_TYPES: PointTypeItem[] = [
  {
    id: 'TYP-001',
    typeCode: 'CPU_USAGE',
    typeName: 'CPU使用率监控',
    unit: '%',
    aggregation: 'AVG',
    isSystem: true,
    description: '服务器主机及容器级CPU综合占用百分比',
    pointCount: 14,
  },
  {
    id: 'TYP-002',
    typeCode: 'MEM_CONSUME',
    typeName: '内存占用率',
    unit: '%',
    aggregation: 'MAX',
    isSystem: true,
    description: '包含JVM堆内存与物理内存消耗量',
    pointCount: 18,
  },
  {
    id: 'TYP-003',
    typeCode: 'TCP_CONN_STATS',
    typeName: 'TCP连接状态统计',
    unit: '连接数',
    aggregation: 'SUM',
    isSystem: true,
    description: '监控ESTABLISHED与TIME_WAIT网络套接字',
    pointCount: 9,
  },
  {
    id: 'TYP-004',
    typeCode: 'DISK_IO_LATENCY',
    typeName: '磁盘IO访问延迟',
    unit: 'ms',
    aggregation: 'MAX',
    isSystem: false,
    description: '监测指定挂载盘写入与读取的等待耗时',
    pointCount: 6,
  },
  {
    id: 'TYP-005',
    typeCode: 'CGI_REQUEST_QPS',
    typeName: 'CGI接口请求吞吐量',
    unit: 'QPS',
    aggregation: 'SUM',
    isSystem: false,
    description: '业务后端API每秒调用次数与成功比率',
    pointCount: 22,
  },
  {
    id: 'TYP-006',
    typeCode: 'LOG_INGEST_RATE',
    typeName: '日志写入速率',
    unit: '条/s',
    aggregation: 'SUM',
    isSystem: false,
    description: '业务日志采集Agent的单机与集群上报流速',
    pointCount: 11,
  },
  {
    id: 'TYP-007',
    typeCode: 'BROWSER_API_LATENCY',
    typeName: '浏览器端API耗时P90',
    unit: 'ms',
    aggregation: 'AVG',
    isSystem: false,
    description: '真实用户端上报的页面加载与AJAX耗时',
    pointCount: 8,
  },
];

// 3.4.2.2 监控点数据
export const INITIAL_MONITOR_POINTS: MonitorPointItem[] = [
  {
    id: 'MP-01',
    pointId: 'PT-CPU-001',
    pointCode: 'PT-CPU-001',
    pointName: 'CPU使用率突增监控',
    typeCode: 'CPU_USAGE',
    typeName: 'CPU使用率监控',
    targetApp: '商城业务中心',
    targetModule: 'user-auth-service',
    intervalSec: 10,
    period: '10s',
    dataType: '瞬时值 (GAUGE)',
    valueType: '百分比 (%)',
    chartType: '折线图 (Line)',
    description: '监控用户认证微服务主机单核及全核CPU占用突增与抖动',
    status: 'ENABLED',
    createdTime: '2026-01-12 10:30',
    creator: 'admin',
    unit: '%',
    intervalSeconds: 10,
    reportMethod: 'PUSH',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    latestValue: 64.2,
    updateTime: '10秒前',
  },
  {
    id: 'MP-02',
    pointId: 'PT-MEM-003',
    pointCode: 'PT-MEM-003',
    pointName: 'JVM老年代内存越界',
    typeCode: 'MEM_CONSUME',
    typeName: '内存占用率',
    targetApp: '商城业务中心',
    targetModule: 'order-pay-gateway',
    intervalSec: 15,
    period: '15s',
    dataType: '瞬时值 (GAUGE)',
    valueType: '百分比 (%)',
    chartType: '面积图 (Area)',
    description: '追踪订单支付核心服务JVM堆内存分配及老年代回收占比',
    status: 'ENABLED',
    createdTime: '2026-02-04 14:15',
    creator: 'ops_li',
    unit: '%',
    intervalSeconds: 15,
    reportMethod: 'PUSH',
    app: '商城业务中心 (mall-app)',
    module: 'order-pay-gateway',
    latestValue: 78.5,
    updateTime: '5秒前',
  },
  {
    id: 'MP-03',
    pointId: 'PT-TCP-008',
    pointCode: 'PT-TCP-008',
    pointName: 'TCP TIME_WAIT堆积预警',
    typeCode: 'TCP_CONN_STATS',
    typeName: 'TCP连接状态统计',
    targetApp: '公共网关体系',
    targetModule: 'api-proxy-nginx',
    intervalSec: 5,
    period: '5s',
    dataType: '原始值 (RAW)',
    valueType: '整数 (Integer)',
    chartType: '柱状图 (Bar)',
    description: '统计入口Nginx高并发代理TIME_WAIT套接字总数，防止端口耗尽',
    status: 'ENABLED',
    createdTime: '2026-02-18 09:20',
    creator: 'zhang_dev',
    unit: '个',
    intervalSeconds: 5,
    reportMethod: 'PUSH',
    app: '公共网关体系 (gateway-core)',
    module: 'api-proxy-nginx',
    latestValue: 4230,
    updateTime: '3秒前',
  },
  {
    id: 'MP-04',
    pointId: 'PT-DISK-002',
    pointCode: 'PT-DISK-002',
    pointName: '数据盘IO写入延迟',
    typeCode: 'DISK_IO_LATENCY',
    typeName: '磁盘IO访问延迟',
    targetApp: '数据智能中台',
    targetModule: 'log-collector-agent',
    intervalSec: 30,
    period: '30s',
    dataType: '差值 (DELTA)',
    valueType: '毫秒 (ms)',
    chartType: '折线图 (Line)',
    description: '采集日志持久化磁盘块设备写入等待耗时，预防IO堵塞',
    status: 'ENABLED',
    createdTime: '2026-03-01 11:00',
    creator: 'wang_sre',
    unit: 'ms',
    intervalSeconds: 30,
    reportMethod: 'PUSH',
    app: '数据智能中台 (data-infra)',
    module: 'log-collector-agent',
    latestValue: 12.4,
    updateTime: '12秒前',
  },
  {
    id: 'MP-05',
    pointId: 'PT-CGI-005',
    pointCode: 'PT-CGI-005',
    pointName: 'CGI请求错误率监控',
    typeCode: 'CGI_REQUEST_QPS',
    typeName: 'CGI接口请求吞吐量',
    targetApp: '商城业务中心',
    targetModule: 'user-auth-service',
    intervalSec: 10,
    period: '10s',
    dataType: '累计值 (COUNTER)',
    valueType: '浮点数 (Float)',
    chartType: '仪表盘 (Gauge)',
    description: '统计用户认证鉴权CGI非200状态码占比及异常突发',
    status: 'ENABLED',
    createdTime: '2026-03-15 16:45',
    creator: 'admin',
    unit: '%',
    intervalSeconds: 10,
    reportMethod: 'PULL',
    app: '商城业务中心 (mall-app)',
    module: 'user-auth-service',
    latestValue: 0.18,
    updateTime: '8秒前',
  },
  {
    id: 'MP-06',
    pointId: 'PT-LOG-009',
    pointCode: 'PT-LOG-009',
    pointName: '日志写入频控突发',
    typeCode: 'LOG_INGEST_RATE',
    typeName: '日志写入速率',
    targetApp: '财务计费系统',
    targetModule: 'billing-calc-job',
    intervalSec: 10,
    period: '10s',
    dataType: '累计值 (COUNTER)',
    valueType: '整数 (Integer)',
    chartType: '柱状图 (Bar)',
    description: '对账批处理作业每秒日志采集流速监控',
    status: 'DISABLED',
    createdTime: '2026-04-02 18:20',
    creator: 'wang_sre',
    unit: '条/s',
    intervalSeconds: 10,
    reportMethod: 'PUSH',
    app: '财务计费系统 (billing-srv)',
    module: 'billing-calc-job',
    latestValue: 850,
    updateTime: '25秒前',
  },
];

// 3.4.2.3 监控点视图数据
export const INITIAL_POINT_VIEWS: PointViewItem[] = [
  {
    id: 'PV-01',
    viewId: 'VIEW-CORE-AUTH',
    viewCode: 'VIEW-CORE-AUTH',
    viewName: '用户认证集群全景大屏',
    boundMachine: '10.24.12.88, 10.24.12.89',
    boundMachines: ['10.24.12.88', '10.24.12.89'],
    description: '聚合认证服务的CPU、内存、TCP连接数与CGI吞吐综合看板',
    creator: 'admin (超级管理员)',
    createdTime: '2026-09-08 16:30',
    pointCount: 4,
    points: ['PT-CPU-001', 'PT-MEM-003', 'PT-TCP-008', 'PT-CGI-005'],
    pointIds: ['PT-CPU-001', 'PT-MEM-003', 'PT-TCP-008', 'PT-CGI-005'],
    layoutType: 'GRID_2',
    chartType: 'LINE',
    refreshIntervalSeconds: 30,
    domain: '核心系统监控',
    updatedTime: '2026-09-08 16:30',
    updatedAt: '2026-09-08 16:30',
  },
  {
    id: 'PV-02',
    viewId: 'VIEW-GATEWAY-INSPECT',
    viewCode: 'VIEW-GATEWAY-INSPECT',
    viewName: '网关链路与连接态势视图',
    boundMachine: '10.24.14.12 (北京网关01)',
    boundMachines: ['10.24.14.12'],
    description: '聚焦入口Nginx代理网络套接字、请求延迟与错误分析大盘',
    creator: 'ops_zhang (运维专家)',
    createdTime: '2026-09-07 11:20',
    pointCount: 3,
    points: ['PT-TCP-008', 'PT-CGI-005', 'PT-LOG-009'],
    pointIds: ['PT-TCP-008', 'PT-CGI-005', 'PT-LOG-009'],
    layoutType: 'GRID_3',
    chartType: 'AREA',
    refreshIntervalSeconds: 15,
    domain: '公共网关体系',
    updatedTime: '2026-09-07 11:20',
    updatedAt: '2026-09-07 11:20',
  },
  {
    id: 'PV-03',
    viewId: 'VIEW-STORAGE-LOGGING',
    viewCode: 'VIEW-STORAGE-LOGGING',
    viewName: '日志上报与磁盘IO看板',
    boundMachine: '10.24.16.55, 10.24.12.90',
    boundMachines: ['10.24.16.55', '10.24.12.90'],
    description: '采集Agent写入速率与机器底层挂载IOPS及存储延迟',
    creator: 'wang_sre (存储运维)',
    createdTime: '2026-09-05 09:15',
    pointCount: 2,
    points: ['PT-DISK-002', 'PT-LOG-009'],
    pointIds: ['PT-DISK-002', 'PT-LOG-009'],
    layoutType: 'ROW',
    chartType: 'BAR',
    refreshIntervalSeconds: 60,
    domain: '数据基础架构',
    updatedTime: '2026-09-05 09:15',
    updatedAt: '2026-09-05 09:15',
  },
];

// 3.4.2.4 告警配置数据
export const INITIAL_ALARM_CONFIGS: AlarmConfigItem[] = [
  {
    id: 'AC-101',
    pointId: 'PT-CPU-001',
    pointCode: 'PT-CPU-001',
    pointName: 'CPU使用率突增监控',
    alarmTarget: '单机',
    targetType: 'MACHINE',
    targetId: '10.24.12.88',
    targetValue: '10.24.12.88 (上海节点01)',
    targetName: 'sh-mall-auth-01 (10.24.12.88)',
    alarmType: '阈值上限告警',
    shieldStatus: '未屏蔽',
    operator: '>=',
    threshold: 85,
    unit: '%',
    level: 'CRITICAL',
    durationSeconds: 120,
    durationMinutes: 2,
    noticeChannels: ['WECHAT', 'SMS', 'EMAIL'],
    notifyChannels: ['WECHAT', 'SMS', 'EMAIL'],
    receivers: ['ops-duty@corp.com', 'admin@corp.com'],
    isShielded: false,
    enabled: true,
    createdTime: '2026-09-08 10:20:00',
  },
  {
    id: 'AC-102',
    pointId: 'PT-MEM-003',
    pointCode: 'PT-MEM-003',
    pointName: 'JVM老年代内存越界',
    alarmTarget: '视图',
    targetType: 'VIEW',
    targetId: 'VIEW-CORE-AUTH',
    targetValue: 'VIEW-CORE-AUTH (认证大盘)',
    targetName: '用户认证集群全景大屏',
    alarmType: '阈值上限告警',
    shieldStatus: '未屏蔽',
    operator: '>=',
    threshold: 80,
    unit: '%',
    level: 'MAJOR',
    durationSeconds: 180,
    durationMinutes: 3,
    noticeChannels: ['WECHAT', 'EMAIL'],
    notifyChannels: ['WECHAT', 'EMAIL'],
    receivers: ['mall-dev@corp.com'],
    isShielded: false,
    enabled: true,
    createdTime: '2026-09-07 14:10:00',
  },
  {
    id: 'AC-103',
    pointId: 'PT-TCP-008',
    pointCode: 'PT-TCP-008',
    pointName: 'TCP TIME_WAIT堆积预警',
    alarmTarget: '单机',
    targetType: 'MACHINE',
    targetId: '10.24.14.12',
    targetValue: '10.24.14.12 (北京网关01)',
    targetName: 'bj-gateway-nginx-01 (10.24.14.12)',
    alarmType: '异常波动告警',
    shieldStatus: '已屏蔽',
    operator: '>=',
    threshold: 6000,
    unit: '条',
    level: 'WARNING',
    durationSeconds: 300,
    durationMinutes: 5,
    noticeChannels: ['WECHAT'],
    notifyChannels: ['WECHAT'],
    receivers: ['net-ops@corp.com'],
    isShielded: true,
    shieldUntil: '2026-09-10 12:00:00',
    enabled: true,
    createdTime: '2026-09-06 17:40:00',
  },
  {
    id: 'AC-104',
    pointId: 'PT-DISK-002',
    pointCode: 'PT-DISK-002',
    pointName: '数据盘IO写入延迟',
    alarmTarget: '单机',
    targetType: 'MACHINE',
    targetId: '10.24.16.55',
    targetValue: '10.24.16.55 (日志中心)',
    targetName: 'sh-data-collector-01 (10.24.16.55)',
    alarmType: '连续超时告警',
    shieldStatus: '未屏蔽',
    operator: '>=',
    threshold: 50,
    unit: 'ms',
    level: 'WARNING',
    durationSeconds: 300,
    durationMinutes: 5,
    noticeChannels: ['WEBHOOK'],
    notifyChannels: ['WEBHOOK'],
    receivers: ['disk-sre@corp.com'],
    isShielded: false,
    enabled: false,
    createdTime: '2026-09-05 15:30:00',
  },
];

// 3.4.3.1 应用数据
export const INITIAL_APPS: AppItem[] = [
  {
    id: 'APP-01',
    appCode: 'mall-app',
    appName: '商城业务中心',
    owner: '张经理 (zhang_pm)',
    department: '新零售电商事业部',
    env: 'Production',
    moduleCount: 6,
    createdTime: '2025-08-10',
    description: '包含用户认证、商品展示、订单处理与支付闭环的核心电商微服务集群',
  },
  {
    id: 'APP-02',
    appCode: 'gateway-core',
    appName: '公共网关体系',
    owner: '李架构 (li_arch)',
    department: '基础平台技术部',
    env: 'Production',
    moduleCount: 4,
    createdTime: '2025-06-15',
    description: '承载所有外部流量统一鉴权、限流、灰度路由与SSL卸载的高性能代理网关',
  },
  {
    id: 'APP-03',
    appCode: 'data-hub',
    appName: '数据智能中台',
    owner: '王总监 (wang_data)',
    department: '大数据研发部',
    env: 'Production',
    moduleCount: 8,
    createdTime: '2025-09-01',
    description: '全链路业务日志清洗、上报归档、实时流计算与离线数仓ETL',
  },
  {
    id: 'APP-04',
    appCode: 'billing-srv',
    appName: '财务计费系统',
    owner: '陈财务 (chen_fin)',
    department: '清结算中台部',
    env: 'Production',
    moduleCount: 3,
    createdTime: '2025-11-20',
    description: '商家结算对账、资金分账流水校验与合规审计报表系统',
  },
];

// 3.4.3.2 模块数据
export const INITIAL_MODULES: ModuleItem[] = [
  {
    id: 'MOD-01',
    moduleCode: 'user-auth-service',
    moduleName: '用户认证鉴权服务',
    appCode: 'mall-app',
    appName: '商城业务中心',
    moduleType: 'SERVICE',
    language: 'Java / Spring Boot 3.2',
    port: 8081,
    healthPath: '/actuator/health',
  },
  {
    id: 'MOD-02',
    moduleCode: 'order-pay-gateway',
    moduleName: '订单支付网关',
    appCode: 'mall-app',
    appName: '商城业务中心',
    moduleType: 'SERVICE',
    language: 'Go / Gin',
    port: 8085,
    healthPath: '/healthz',
  },
  {
    id: 'MOD-03',
    moduleCode: 'api-proxy-nginx',
    moduleName: '入口API代理分发',
    appCode: 'gateway-core',
    appName: '公共网关体系',
    moduleType: 'GATEWAY',
    language: 'OpenResty / Lua',
    port: 443,
    healthPath: '/nginx_status',
  },
  {
    id: 'MOD-04',
    moduleCode: 'log-collector-agent',
    moduleName: '日志采集代理程序',
    appCode: 'data-hub',
    appName: '数据智能中台',
    moduleType: 'JOB',
    language: 'Rust',
    port: 9092,
    healthPath: '/metrics',
  },
  {
    id: 'MOD-05',
    moduleCode: 'billing-calc-job',
    moduleName: '清分跑批定时任务',
    appCode: 'billing-srv',
    appName: '财务计费系统',
    moduleType: 'JOB',
    language: 'Python / Celery',
    port: 8099,
    healthPath: '/status',
  },
];

// 3.4.3.3 日志配置数据
export const INITIAL_LOG_CONFIGS: LogConfigItem[] = [
  {
    id: 'CFG-01',
    configCode: 'CFG-MALL-AUTH',
    configName: '用户认证标准日志采集',
    appCode: 'mall-app',
    appName: '商城业务中心',
    moduleCode: 'user-auth-service',
    moduleName: '用户认证鉴权服务',
    logType: 'JSON',
    filePath: '/data/logs/mall-app/user-auth-service/*.log',
    rateLimitPerSec: 5000,
    burstLimit: 12000,
    encoding: 'UTF-8',
    sampleRate: 100,
    enabled: true,
  },
  {
    id: 'CFG-02',
    configCode: 'CFG-GATEWAY-ACCESS',
    configName: '网关统一访问日志上报',
    appCode: 'gateway-core',
    appName: '公共网关体系',
    moduleCode: 'api-proxy-nginx',
    moduleName: '入口API代理分发',
    logType: 'DELIMITED',
    filePath: '/var/log/nginx/access_json.log',
    rateLimitPerSec: 25000,
    burstLimit: 50000,
    encoding: 'UTF-8',
    sampleRate: 80,
    enabled: true,
  },
  {
    id: 'CFG-03',
    configCode: 'CFG-BILLING-ERROR',
    configName: '计费异常追踪堆栈采集',
    appCode: 'billing-srv',
    appName: '财务计费系统',
    moduleCode: 'billing-calc-job',
    moduleName: '清分跑批定时任务',
    logType: 'REGEX',
    filePath: '/data/logs/billing-srv/*.error',
    rateLimitPerSec: 1000,
    burstLimit: 3000,
    encoding: 'UTF-8',
    sampleRate: 100,
    enabled: true,
  },
];

// 3.3.3 Linux基础资源监控模拟数据
export const LINUX_RESOURCE_DATA = {
  systemOverview: {
    hostname: 'sh-mall-auth-01.prod',
    os: 'Linux Enterprise 5.15.0-89-generic (x86_64)',
    uptime: '118天 14小时 23分',
    loadAvg: { '1m': 2.45, '5m': 3.12, '15m': 2.89 },
    cpuCount: 16,
    totalProcesses: 428,
    runningProcesses: 3,
    zombieProcesses: 0,
  },
  memoryTable: [
    { type: '物理内存 (Total)', size: '64.00 GB', used: '44.80 GB (70.0%)', free: '9.20 GB', shared: '1.40 GB' },
    { type: '缓冲区 (Buffers/Cached)', size: '10.00 GB', used: '8.60 GB', free: '1.40 GB', shared: '-' },
    { type: '交换分区 (Swap)', size: '16.00 GB', used: '1.20 GB (7.5%)', free: '14.80 GB', shared: '-' },
  ],
  topProcesses: [
    { pid: 14092, user: 'appuser', cpu: '38.5%', mem: '24.2%', name: 'java -jar user-auth-service.jar' },
    { pid: 14104, user: 'appuser', cpu: '18.2%', mem: '12.0%', name: 'java -jar user-auth-service.jar' },
    { pid: 3891, user: 'root', cpu: '4.8%', mem: '2.1%', name: 'log-collector-agent --daemon' },
    { pid: 1102, user: 'systemd', cpu: '1.1%', mem: '0.4%', name: 'systemd-journald' },
  ],
  tcpUdpStats: [
    { proto: 'TCP', state: 'ESTABLISHED', count: 4820, desc: '正常传输中连接' },
    { proto: 'TCP', state: 'TIME_WAIT', count: 8420, desc: '等待关闭连接 (告警偏高)' },
    { proto: 'TCP', state: 'CLOSE_WAIT', count: 124, desc: '被动关闭等待释放' },
    { proto: 'TCP', state: 'LISTEN', count: 46, desc: '本地服务监听端口' },
    { proto: 'TCP', state: 'SYN_SENT / RECV', count: 18, desc: '握手半开连接' },
    { proto: 'UDP', state: 'UNCONNECTED', count: 240, desc: 'DNS/Syslog无连接套接字' },
  ],
  diskIoTable: [
    { mount: '/', device: '/dev/nvme0n1p1', fstype: 'ext4', total: '100 GB', used: '34.2 GB (34%)', readIops: 240, writeIops: 820, readMb: '4.2 MB/s', writeMb: '18.4 MB/s', awaitMs: 1.8 },
    { mount: '/data', device: '/dev/nvme1n1', fstype: 'xfs', total: '1024 GB', used: '712.0 GB (69%)', readIops: 1240, writeIops: 3820, readMb: '32.5 MB/s', writeMb: '94.2 MB/s', awaitMs: 64.2 },
    { mount: '/var/log', device: '/dev/nvme0n1p2', fstype: 'ext4', total: '200 GB', used: '112.5 GB (56%)', readIops: 120, writeIops: 1940, readMb: '1.2 MB/s', writeMb: '42.0 MB/s', awaitMs: 3.4 },
  ],
};

// 3.3.4 浏览器端监控模拟数据
export const BROWSER_MONITOR_DATA = {
  osDistribution: [
    { name: 'Windows 11/10', value: 48, fill: '#3b82f6' },
    { name: 'macOS Sonoma/Ventura', value: 24, fill: '#6366f1' },
    { name: 'Android 14/13', value: 16, fill: '#10b981' },
    { name: 'iOS 17/18', value: 9, fill: '#f59e0b' },
    { name: 'Linux / Others', value: 3, fill: '#8b5cf6' },
  ],
  browserVersions: [
    { name: 'Chrome 128+', share: 58.4, users: '1,420,800' },
    { name: 'Safari 17.5+', share: 18.2, users: '442,100' },
    { name: 'Edge 128+', share: 12.1, users: '294,000' },
    { name: 'WeChat Webview', share: 6.8, users: '165,200' },
    { name: 'Firefox 130+', share: 3.2, users: '77,800' },
    { name: '其他 / 嵌入核', share: 1.3, users: '31,600' },
  ],
  geoDistribution: [
    { region: '广东 (广州/深圳)', visitors: 589200, percentage: '24.2%' },
    { region: '浙江 (杭州/宁波)', visitors: 394000, percentage: '16.2%' },
    { region: '北京 (海淀/朝阳)', visitors: 368100, percentage: '15.1%' },
    { region: '上海 (浦东/徐汇)', visitors: 341000, percentage: '14.0%' },
    { region: '江苏 (南京/苏州)', visitors: 289400, percentage: '11.9%' },
    { region: '四川 (成都)', visitors: 162000, percentage: '6.6%' },
    { region: '海外及其他', visitors: 290100, percentage: '12.0%' },
  ],
  apiLatencyTimeline: [
    { time: '00:00', p50: 42, p90: 110, p99: 320 },
    { time: '04:00', p50: 38, p90: 95, p99: 280 },
    { time: '08:00', p50: 55, p90: 145, p99: 450 },
    { time: '12:00', p50: 82, p90: 210, p99: 680 },
    { time: '16:00', p50: 74, p90: 195, p99: 590 },
    { time: '20:00', p50: 95, p90: 260, p99: 890 },
    { time: '22:00', p50: 68, p90: 170, p99: 510 },
  ],
};

// 3.3.5.1 监控系统-常用 视图模拟数据
export const COMMON_VIEW_DATA = {
  logIngestTrends: [
    { time: '00:00', countK: 45, mbVolume: 120 },
    { time: '02:00', countK: 30, mbVolume: 82 },
    { time: '04:00', countK: 22, mbVolume: 58 },
    { time: '06:00', countK: 38, mbVolume: 96 },
    { time: '08:00', countK: 120, mbVolume: 340 },
    { time: '10:00', countK: 260, mbVolume: 690 },
    { time: '12:00', countK: 310, mbVolume: 810 },
    { time: '14:00', countK: 280, mbVolume: 740 },
    { time: '16:00', countK: 330, mbVolume: 880 },
    { time: '18:00', countK: 290, mbVolume: 790 },
    { time: '20:00', countK: 360, mbVolume: 940 },
    { time: '22:00', countK: 220, mbVolume: 590 },
  ],
  loginAndCgiRequests: [
    { time: '00:00', loginSuccess: 1200, loginFail: 18, cgiQps: 3400, successRate: 99.8 },
    { time: '04:00', loginSuccess: 450, loginFail: 8, cgiQps: 1800, successRate: 99.9 },
    { time: '08:00', loginSuccess: 4800, loginFail: 62, cgiQps: 8200, successRate: 99.7 },
    { time: '10:00', loginSuccess: 9200, loginFail: 110, cgiQps: 16500, successRate: 99.6 },
    { time: '12:00', loginSuccess: 11400, loginFail: 145, cgiQps: 21000, successRate: 99.4 },
    { time: '14:00', loginSuccess: 9800, loginFail: 98, cgiQps: 18200, successRate: 99.7 },
    { time: '16:00', loginSuccess: 10800, loginFail: 122, cgiQps: 19800, successRate: 99.6 },
    { time: '20:00', loginSuccess: 13200, loginFail: 184, cgiQps: 24500, successRate: 99.3 },
    { time: '22:00', loginSuccess: 7600, loginFail: 79, cgiQps: 14200, successRate: 99.8 },
  ],
};

// 3.3.6 服务器查看 模拟数据
export const SERVER_STATUS_DATA = {
  diskWriteTrends: [
    { time: '00:00', diskNvme0: 12.4, diskNvme1: 42.1 },
    { time: '03:00', diskNvme0: 8.1, diskNvme1: 28.4 },
    { time: '06:00', diskNvme0: 14.5, diskNvme1: 39.0 },
    { time: '09:00', diskNvme0: 24.2, diskNvme1: 88.5 },
    { time: '12:00', diskNvme0: 31.0, diskNvme1: 112.4 },
    { time: '15:00', diskNvme0: 28.4, diskNvme1: 96.2 },
    { time: '18:00', diskNvme0: 34.8, diskNvme1: 128.0 },
    { time: '21:00', diskNvme0: 42.0, diskNvme1: 144.5 },
    { time: '23:00', diskNvme0: 18.5, diskNvme1: 64.0 },
  ],
  vmemAndLatencyTrends: [
    { time: '00:00', pageInRate: 140, pageOutRate: 320, accessLatencyMs: 1.2 },
    { time: '03:00', pageInRate: 85, pageOutRate: 180, accessLatencyMs: 0.9 },
    { time: '06:00', pageInRate: 110, pageOutRate: 240, accessLatencyMs: 1.1 },
    { time: '09:00', pageInRate: 420, pageOutRate: 890, accessLatencyMs: 2.8 },
    { time: '12:00', pageInRate: 680, pageOutRate: 1450, accessLatencyMs: 4.6 },
    { time: '15:00', pageInRate: 590, pageOutRate: 1280, accessLatencyMs: 3.9 },
    { time: '18:00', pageInRate: 720, pageOutRate: 1620, accessLatencyMs: 5.2 },
    { time: '21:00', pageInRate: 850, pageOutRate: 1980, accessLatencyMs: 6.4 },
    { time: '23:00', pageInRate: 310, pageOutRate: 720, accessLatencyMs: 2.1 },
  ],
};

// 基础用户状态
export const MOCK_USER = {
  username: 'admin',
  realName: '系统超级管理员',
  name: '系统超级管理员',
  role: 'SUPER_ADMIN',
  department: '基础平台架构与SRE运维部',
  avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

// 别名导出以兼容不同组件引用
export const MOCK_REALTIME_LOGS = INITIAL_LOGS;
export const MOCK_LOG_FILES = INITIAL_LOG_FILES;
export const MOCK_MACHINES = INITIAL_MACHINES;
export const INITIAL_ALARM_RULES = INITIAL_ALARM_CONFIGS;
export const INITIAL_LOG_SOURCE_CONFIGS = INITIAL_LOG_CONFIGS.map((cfg) => ({
  ...cfg,
  filePathPattern: cfg.filePath,
  logFormat: (cfg.logType === 'DELIMITED' ? 'DELIMITER' : cfg.logType === 'STANDARD_TEXT' ? 'TEXT' : cfg.logType) as any,
  collectStrategy: 'SINGLE_LINE' as const,
  multilinePattern: '^\\d{4}-\\d{2}-\\d{2}',
  fieldExtractRegex: '(?<timestamp>\\S+) \\[(?<level>\\w+)\\] (?<message>.*)',
  status: 'ACTIVE' as const,
  updatedAt: '刚刚',
}));
